name: Update talosctl winget package-PUSH
on: [push]
jobs:
  winget:
    name: Publish talosctl winget package
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
        working-directory: ${{ github.workspace }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      WINGET_PAT: ${{ secrets.WINGET_PAT }}
    steps:
      - name: Checkout code 👋
        uses: actions/checkout@v4
      - name: Create manifest and submit PR 📦
        run: |
          ./createManifest.ps1