name: Publish winget package-Cron
on:
  push:
  schedule:
    - cron:  '23 23 * * *'
jobs:
  winget:
    name: Publish winget package
    runs-on: windows-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # updated local manifest files to this repo
      contents: write
    defaults:
      run:
        shell: pwsh
        working-directory: ${{ github.workspace }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      WINGET_CREATE_GITHUB_TOKEN: ${{ secrets.WINGET_PAT }}
    steps:
      - name: Checkout code 👋
        uses: actions/checkout@v5
      - name: Create manifest and submit PR 📦
        run: |
          ./createManifest.ps1