name: Sync Fork

on:
  schedule:
    - cron: '0 0 1 * *' # every month once
  workflow_dispatch: # on button click

jobs:
  fork-sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          repo: winget-pkgs
          base: master
          head: master
          token: ${{ secrets.WINGET_PAT }}
          owner: nebula-it
