name: Sync Fork

on:
  schedule:
    - cron: '0 0 1 * *' # every month once
  workflow_dispatch: # on button click

jobs:
  fork-sync:

    runs-on: ubuntu-latest

    steps:
      - run: gh repo sync $REPOSITORY -b $BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: winget-pkgs
          BRANCH_NAME: master
